// <auto-generated />
namespace PRO_finder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class worktest1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(worktest1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111418451_worktest1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
