// <auto-generated />
namespace PRO_finder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class workseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workseed));
        
        string IMigrationMetadata.Id
        {
            get { return "202108201025322_workseed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
