// <auto-generated />
namespace PRO_finder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210828changetalentTool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210828changetalentTool));
        
        string IMigrationMetadata.Id
        {
            get { return "202108280828145_''2021-08-28 change talentTool'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
