// <auto-generated />
namespace PRO_finder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210921updatedatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210921updatedatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210743303_2021-09-21 update database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
