// <auto-generated />
namespace PRO_finder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210926 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210926));
        
        string IMigrationMetadata.Id
        {
            get { return "202109261129157_2021-09-26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
